name: simpliflat
description: One stop solution for all the problems of flatmates in a house

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: '>=0.11.3+12'
  shared_preferences: "0.4.3"
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.9
  uuid:
  firebase_auth: ^0.11.1
  sqflite: ^1.1.6+3
  path_provider:
  timeago: ^2.0.16
  firebase_messaging:
  flutter_slidable: ^0.5.3
  flutter_local_notifications: ^0.7.1
  url_launcher: ^5.0.3
  share: ^0.6.3+4
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Italic.ttf
          style: italic
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat-bold.ttf
        - asset: fonts/Montserrat-SemiBold.otf
          weight: 700
    - family: IconsCustom
      fonts:
        - asset: fonts/IconsCustom.ttf
    - family: Satisfy
      fonts:
          - asset: fonts/Satisfy-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
