/// Flutter icons IconsCustom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconsCustom
///      fonts:
///       - asset: fonts/IconsCustom.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
///
import 'package:flutter/widgets.dart';

class IconsCustom {
  IconsCustom._();

  static const _kFontFam = 'IconsCustom';

  static const IconData tasks_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bullhorn = const IconData(0xe801, fontFamily: _kFontFam);
}
